stages:
  - build
  - test
  - deploy

default:
  image: maven
  tags:
    - docker

mavenBuild:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target
    expire_in: 1 week

unitTests:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  tags:
    - docker
  script: mvn deploy -DskipTests ; echo $MAVEN_REPO_USER ; printenv ; env
  only:
    - master
  artifacts:
    paths:
      - target/*.jar
    expire_in: 30 days
