stages:
  - lib-build
  - lib-test
  - lib-deploy
  - processor-build
  - processor-test
  - processor-deploy
  - tools-build
  - tools-test
  - tools-deploy

default:
  image: gradle:6.7-jdk15
  tags:
    - docker

include:
  - local: ci-configs/auriga_libs_ci.yml
  - local: ci-configs/auriga_java_ci.yml
  - local: ci-configs/auriga_kotlin_ci.yml
  - local: ci-configs/auriga_buildtool_plugins_ci.yml