stages:
  - build-libs
  - build-plugins
  - test
  - deploy

default:
  image: maven
  tags:
    - docker

mavenBuild:
  stage: build-libs
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - jdk-8-target/target
      - jdk-9-target/target
    expire_in: 1 week

kotlinPluginBuild:
  stage: build-libs
  image: gradle:6.7.1-jdk15
  variables:
    GRADLE_OPTS: "-Dfile.encoding=UTF-8 -Duser.country=DE -Duser.language=de"
  script:
    - env
    - printenv
    - cd auriga-kotlin-plugin
    - gradle --stacktrace --debug build
  after_script:
    - cat /home/gradle/.gradle/daemon/6.7.1/*
  artifacts:
    paths:
      - auriga-kotlin-plugin/build
    expire_in: 1 week

gradlePluginBuild:
  stage: build-plugins
  image: gradle:6.7
  dependencies:
    - kotlinPluginBuild
  script:
    - cd auriga-gradle-plugin
    - gradle publishToMavenLocal
  artifacts:
    paths:
      - auriga-gradle-plugin/build
    expire_in: 1 week

unitTests:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  tags:
    - docker
  script: mvn deploy -DskipTests
  only:
    - master
  artifacts:
    paths:
      - jdk-8-target/target/*.jar
      - jdk-9-target/target/*.jar
    expire_in: 30 days

gradlePluginPublish:
  stage: deploy
  image: gradle:6.7
  script:
    - cd auriga-gradle-plugin
    - gradle publish
  artifacts:
    paths:
      - auriga-gradle-plugin/build/libs/*.jar
    expire_in: 1 week

kotlinPluginPublish:
  stage: deploy
  image: gradle:6.7
  script:
    - cd auriga-kotlin-plugin
    - gradle publish
  artifacts:
    paths:
      - auriga-kotlin-plugin/build/libs/*.jar
    expire_in: 1 week

