stages:
  - build
  - test
  - deploy

default:
  image: maven
  tags:
    - docker

mavenBuild:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - jdk-8-target/target
      - jdk-11-target/target
    expire_in: 1 week

unitTests:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  tags:
    - docker
  script: mvn deploy -DskipTests
  only:
    - master
  artifacts:
    paths:
      - jdk-8-target/target/*.jar
      - jdk-11-target/target/*.jar
    expire_in: 30 days
