stages:
  - libs-build
  - libs-test
  - libs-deploy
  - tools-build
  - tools-test
  - tools-deploy

default:
  image: maven
  tags:
    - docker

include:
  - local: ./ci-configs/auriga_java_ci.yml
  - local: ./ci-configs/auriga_kotlin_ci.yml
  - local: ./ci-configs/auriga_buildtool_plugins_ci.yml